group 'net.kikuchy.plain_notification_token'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 36
    namespace 'net.kikuchy.plain_notification_token'

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    dependencies {
        implementation 'com.google.firebase:firebase-messaging:23.4.0'
        implementation 'androidx.annotation:annotation:1.0.0'
        implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
    }
}
